// ============================================================================
// CRM Reminder Task CRUD — Create/update/close follow-up tasks for Cat
// ============================================================================
//
// Manages CRM tasks for document follow-up reminders:
// - Deduplication by title pattern ("Follow up: Need docs")
// - Update existing task body on subsequent reminder cycles (no duplicates)
// - Auto-close when all docs received
//
// All functions are non-fatal: errors are logged as warnings, never thrown.
// This ensures reminder failures never block the main pipeline.
//
// Pattern copied from src/crm/tasks.ts (taskFetch helper) to avoid
// breaking existing tasks.ts internals.

import { crmConfig, devPrefix } from '../crm/config.js';
import { CrmApiError, CrmRateLimitError, CrmAuthError } from '../crm/errors.js';
import { addBusinessDays } from './business-days.js';

// ============================================================================
// Public API
// ============================================================================

/**
 * Searches for an existing reminder task on a contact.
 *
 * Looks for tasks with title containing "Follow up: Need docs".
 * Non-fatal: returns null on any error.
 *
 * @param contactId - The CRM contact ID to search tasks for
 * @returns The first matching task, or null if none found or on error
 */
export async function findReminderTask(
  contactId: string,
): Promise<{ id: string; title: string; completed: boolean } | null> {
  try {
    const response = await reminderTaskFetch(`/contacts/${contactId}/tasks`, {
      method: 'GET',
    });

    const data = (await response.json()) as {
      tasks: Array<{ id: string; title: string; completed: boolean }>;
    };

    const match = data.tasks.find((task) => task.title.includes('Follow up: Need docs'));
    return match ? { id: match.id, title: match.title, completed: match.completed } : null;
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.warn(`[findReminderTask] Failed to search tasks for contact: ${message}`);
    return null;
  }
}

/**
 * Creates a new reminder task or updates an existing one (deduplication).
 *
 * - If no existing task: creates with title "Follow up: Need docs - {name}"
 * - If existing task found: updates body + resets dueDate (no duplicate)
 *
 * Non-fatal: catches all errors, logs warnings, returns undefined.
 *
 * @param contactId - The CRM contact ID
 * @param borrowerName - Display name for the task title
 * @param taskBody - Full task body content (generated by generateReminderTaskBody)
 * @returns The task ID (existing or new), or undefined on error
 */
export async function createOrUpdateReminderTask(
  contactId: string,
  borrowerName: string,
  taskBody: string,
): Promise<string | undefined> {
  try {
    const existing = await findReminderTask(contactId);

    if (existing) {
      // Update existing task: new body + reset due date
      await reminderTaskFetch(`/contacts/${contactId}/tasks/${existing.id}`, {
        method: 'PUT',
        body: JSON.stringify({
          body: taskBody,
          dueDate: addBusinessDays(new Date(), 1).toISOString(),
        }),
      });
      return existing.id;
    }

    // No existing task -- create new
    const body = {
      title: devPrefix(`Follow up: Need docs - ${borrowerName}`),
      body: taskBody,
      assignedTo: crmConfig.userIds.cat,
      dueDate: addBusinessDays(new Date(), 1).toISOString(),
      completed: false,
    };

    const response = await reminderTaskFetch(`/contacts/${contactId}/tasks`, {
      method: 'POST',
      body: JSON.stringify(body),
    });

    const data = (await response.json()) as { task: { id: string } };
    return data.task.id;
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.warn(`[createOrUpdateReminderTask] Failed: ${message}`);
    return undefined;
  }
}

/**
 * Closes an existing reminder task when all docs are received.
 *
 * Finds the reminder task by title pattern, marks it as completed if
 * it exists and is not already completed.
 *
 * Non-fatal: catches all errors, logs warnings, never throws.
 *
 * @param contactId - The CRM contact ID
 */
export async function closeReminderTask(contactId: string): Promise<void> {
  try {
    const existing = await findReminderTask(contactId);

    if (!existing || existing.completed) {
      return; // Nothing to close
    }

    await reminderTaskFetch(`/contacts/${contactId}/tasks/${existing.id}`, {
      method: 'PUT',
      body: JSON.stringify({ completed: true }),
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.warn(`[closeReminderTask] Failed: ${message}`);
  }
}

// ============================================================================
// Internal — HTTP helper (same pattern as src/crm/tasks.ts taskFetch)
// ============================================================================

async function reminderTaskFetch(path: string, init: RequestInit): Promise<Response> {
  const url = `${crmConfig.baseUrl}${path}`;

  try {
    const response = await fetch(url, {
      ...init,
      headers: {
        Authorization: `Bearer ${crmConfig.apiKey}`,
        Version: '2021-07-28',
        'Content-Type': 'application/json',
        ...((init.headers as Record<string, string>) ?? {}),
      },
    });

    if (!response.ok) {
      const responseBody = await response.text();

      if (response.status === 429) {
        throw new CrmRateLimitError(responseBody);
      }
      if (response.status === 401) {
        throw new CrmAuthError(responseBody);
      }

      throw new CrmApiError(
        `CRM API error: ${response.status} ${response.statusText}`,
        response.status,
        responseBody,
      );
    }

    return response;
  } catch (error) {
    if (error instanceof CrmApiError) {
      throw error;
    }

    throw new CrmApiError(
      `CRM API request failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
      0,
      '',
    );
  }
}
